import React, { useState, useEffect } from 'react';
import { type AIResult } from '../types';
import { CopyIcon, CheckIcon, ExternalLinkIcon, DownloadIcon, ImageIcon } from './icons';

interface ResultCardProps {
  result: AIResult;
}

const TextSkeletonLoader: React.FC = () => (
    <div className="space-y-3 animate-pulse">
      <div className="h-4 bg-gray-700 rounded w-3/4"></div>
      <div className="h-4 bg-gray-700 rounded w-full"></div>
      <div className="h-4 bg-gray-700 rounded w-5/6"></div>
    </div>
);

const ImageSkeletonLoader: React.FC = () => (
    <div className="w-full aspect-square bg-gray-700 rounded-lg animate-pulse flex items-center justify-center">
        <ImageIcon className="w-16 h-16 text-gray-600" />
    </div>
);

export const ResultCard: React.FC<ResultCardProps> = ({ result }) => {
    const [copied, setCopied] = useState(false);
    const LogoComponent = result.logo;
    const isImageResult = !!result.imageUrl;

    useEffect(() => {
        if (copied) {
            const timer = setTimeout(() => setCopied(false), 2000);
            return () => clearTimeout(timer);
        }
    }, [copied]);

    const handleCopy = () => {
        if(result.response) {
            navigator.clipboard.writeText(result.response);
            setCopied(true);
        }
    };

    const handleDownload = () => {
        if (result.imageUrl) {
            const link = document.createElement('a');
            link.href = result.imageUrl;
            link.download = `${result.name}-${Date.now()}.png`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }
    };

  return (
    <div className="bg-gray-800/50 border border-gray-700 rounded-xl shadow-lg overflow-hidden h-full flex flex-col">
      <header className="flex items-center justify-between p-4 bg-gray-800 border-b border-gray-700">
        <div className="flex items-center gap-3">
          <LogoComponent className="w-6 h-6" />
          <span className="text-lg font-semibold text-white">{result.name}</span>
        </div>
        {isImageResult ? (
            <button 
                onClick={handleDownload}
                className="p-2 rounded-md hover:bg-gray-700 text-gray-400 hover:text-white transition-colors disabled:opacity-50"
                disabled={result.isLoading || !result.imageUrl}
                aria-label="Download image"
                title="Download Image"
            >
                <DownloadIcon className="w-5 h-5" />
            </button>
        ) : (
            <button 
                onClick={handleCopy}
                className="p-2 rounded-md hover:bg-gray-700 text-gray-400 hover:text-white transition-colors disabled:opacity-50"
                disabled={result.isLoading || !result.response}
                aria-label="Copy response"
            >
                {copied ? <CheckIcon className="w-5 h-5 text-green-400" /> : <CopyIcon className="w-5 h-5" />}
            </button>
        )}
      </header>
      <div className="p-5 flex-grow flex flex-col justify-between">
        <div className="flex-grow">
            {result.isLoading ? (
                isImageResult ? <ImageSkeletonLoader /> : <TextSkeletonLoader />
            ) : isImageResult ? (
                result.imageUrl && <img src={result.imageUrl} alt={`Generated by ${result.name}`} className="w-full h-auto rounded-lg object-contain" />
            ) : (
                <p className="text-gray-300 whitespace-pre-wrap">{result.response}</p>
            )}
        </div>
        {!result.isLoading && result.sources && result.sources.length > 0 && (
            <div className="mt-4 pt-4 border-t border-gray-700/50">
                <h4 className="text-sm font-semibold text-gray-400 mb-2">Sources:</h4>
                <ul className="space-y-2">
                    {result.sources.map((source, index) => (
                        <li key={index} className="text-sm truncate">
                            <a 
                                href={source.uri} 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="text-purple-400 hover:text-purple-300 hover:underline transition-colors inline-flex items-center gap-1.5 w-full"
                                title={source.title}
                            >
                                <ExternalLinkIcon className="w-4 h-4 flex-shrink-0" />
                                <span className="truncate">{source.title || new URL(source.uri).hostname}</span>
                            </a>
                        </li>
                    ))}
                </ul>
            </div>
        )}
      </div>
    </div>
  );
};
